version: "3.9"

services:

  app:
    restart: "unless-stopped"
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
