name: Linters

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3

      - 
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - 
        name: Upgrade pip and tools
        run: python -m pip install --upgrade pip setuptools wheel

      - 
        name: Clear pip cache
        run: python -m pip cache purge

      - 
        name: Install dependencies
        run: python -m pip install --requirement requirements-dev.txt

      - 
        name: Run flake8
        run: pflake8 .

      - 
        name: Run isort
        run: isort --profile black --check-only .

      - 
        name: Run black
        run: black --diff --check .

      - 
        name: Run mypy
        run: mypy --show-error-codes stable_gnn
